// ============================================================================
// PREDICATE REGISTRY
// Canonical WorkProof predicate definitions (40 predicates across 8 categories)
// Each entry is a full PredicateDefinition from @gtcx/verification
// ============================================================================

import type { PredicateDefinition, PredicateURI } from '@gtcx/verification';

import type { WorkProofPredicateType } from './types';

function uri(category: string, name: string): PredicateURI {
  return `tradepass://workproof/${category}/${name}` as PredicateURI;
}

/** Canonical URIs for all 40 WorkProof predicate types */
export const WORKPROOF_PREDICATE_URIS: Record<WorkProofPredicateType, PredicateURI> = {
  // Identity
  IdentityVerified: uri('identity', 'verified'),
  RoleHeld: uri('identity', 'role-held'),
  EmploymentActive: uri('identity', 'employment-active'),
  TenureAchieved: uri('identity', 'tenure-achieved'),
  CommunityMembership: uri('identity', 'community-membership'),
  // Production
  CommodityProduced: uri('production', 'commodity-produced'),
  QuantityVerified: uri('production', 'quantity-verified'),
  QualityGraded: uri('production', 'quality-graded'),
  OriginAuthenticated: uri('production', 'origin-authenticated'),
  MethodCompliant: uri('production', 'method-compliant'),
  // Location
  SiteVerified: uri('location', 'site-verified'),
  GeofenceCompliant: uri('location', 'geofence-compliant'),
  LocationConsistent: uri('location', 'location-consistent'),
  EnvironmentalCompliance: uri('location', 'environmental-compliance'),
  // Compliance
  InspectionPassed: uri('compliance', 'inspection-passed'),
  StandardMet: uri('compliance', 'standard-met'),
  GCIScoreRecorded: uri('compliance', 'gci-score-recorded'),
  ViolationFree: uri('compliance', 'violation-free'),
  LicenseValid: uri('compliance', 'license-valid'),
  // Financial
  PaymentReceived: uri('financial', 'payment-received'),
  LoanDisbursed: uri('financial', 'loan-disbursed'),
  RepaymentCompleted: uri('financial', 'repayment-completed'),
  SavingsDeposited: uri('financial', 'savings-deposited'),
  TaxWithheld: uri('financial', 'tax-withheld'),
  // Learning
  ModuleCompleted: uri('learning', 'module-completed'),
  AssessmentPassed: uri('learning', 'assessment-passed'),
  CertificationEarned: uri('learning', 'certification-earned'),
  SkillDemonstrated: uri('learning', 'skill-demonstrated'),
  MentorshipProvided: uri('learning', 'mentorship-provided'),
  // Performance
  ConsistencyMaintained: uri('performance', 'consistency-maintained'),
  QualityThresholdMet: uri('performance', 'quality-threshold-met'),
  ProductivityTarget: uri('performance', 'productivity-target'),
  ReliabilityScore: uri('performance', 'reliability-score'),
  // Community
  PeerEndorsement: uri('community', 'peer-endorsement'),
  ElderAttestation: uri('community', 'elder-attestation'),
  CooperativeMembership: uri('community', 'cooperative-membership'),
  CommunityContribution: uri('community', 'community-contribution'),
  MentorshipReceived: uri('community', 'mentorship-received'),
};

/** Full predicate definitions for all 40 WorkProof predicate types */
export const WORKPROOF_PREDICATES: Record<WorkProofPredicateType, PredicateDefinition> = {
  // ─── Identity Predicates ──────────────────────────────────────────────────
  IdentityVerified: {
    uri: WORKPROOF_PREDICATE_URIS.IdentityVerified,
    name: 'Identity Verified',
    description: 'Subject identity verified through official documentation and/or biometrics',
    domain: 'identity',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: {
      required: ['government_id'],
      optional: ['biometric_face', 'biometric_fingerprint'],
    },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'AuthorityID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.9,
      evidenceWeights: { government_id: 0.7, biometric_face: 0.2, biometric_fingerprint: 0.1 },
      minimumThreshold: 0.7,
    },
    temporal: { validDuration: 'P1Y', renewalRequired: true, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['government document', 'biometric match'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.RoleHeld],
      contextTemplate: 'Identity verified via {{evidenceType}}',
    },
  },
  RoleHeld: {
    uri: WORKPROOF_PREDICATE_URIS.RoleHeld,
    name: 'Role Held',
    description: 'Employment role assigned and active',
    domain: 'identity',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.85, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.6 },
    temporal: {
      validDuration: 'P6M',
      renewalRequired: true,
      monitoringType: 'event_triggered',
      triggers: ['role.granted', 'role.revoked'],
    },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['role assignment document'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.EmploymentActive],
      contextTemplate: 'Role {{value}} assigned',
    },
  },
  EmploymentActive: {
    uri: WORKPROOF_PREDICATE_URIS.EmploymentActive,
    name: 'Employment Active',
    description: 'Subject is actively employed by an operating company',
    domain: 'identity',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.9, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P1M', renewalRequired: true, monitoringType: 'continuous' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['active employment contract'],
      relatedPredicates: [
        WORKPROOF_PREDICATE_URIS.RoleHeld,
        WORKPROOF_PREDICATE_URIS.TenureAchieved,
      ],
      contextTemplate: 'Employment active since {{effectiveAt}}',
    },
  },
  TenureAchieved: {
    uri: WORKPROOF_PREDICATE_URIS.TenureAchieved,
    name: 'Tenure Achieved',
    description: 'Employment duration milestone reached',
    domain: 'identity',
    version: '2.1.0',
    schema: { type: 'number', min: 1 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.95, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.8 },
    temporal: { validDuration: 'P5Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['employment history timeline'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.EmploymentActive],
      contextTemplate: '{{value}} months tenure achieved',
    },
  },
  CommunityMembership: {
    uri: WORKPROOF_PREDICATE_URIS.CommunityMembership,
    name: 'Community Membership',
    description: 'Community or cooperative affiliation verified',
    domain: 'identity',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['witness_attestation'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
      minimumAttestors: 2,
    },
    confidence: {
      baseScore: 0.7,
      evidenceWeights: { witness_attestation: 1.0 },
      minimumThreshold: 0.5,
    },
    temporal: { validDuration: 'P1Y', renewalRequired: true, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['community affiliation records'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.PeerEndorsement],
      contextTemplate: 'Member of {{value}}',
    },
  },

  // ─── Production Predicates ────────────────────────────────────────────────
  CommodityProduced: {
    uri: WORKPROOF_PREDICATE_URIS.CommodityProduced,
    name: 'Commodity Produced',
    description: 'Physical commodity production verified through evidence',
    domain: 'asset',
    version: '2.1.0',
    schema: {
      type: 'object',
      properties: {
        commodity: { type: 'string' },
        quantity: { type: 'number', min: 0 },
        unit: { type: 'string' },
      },
    },
    evidence: { required: ['photo_evidence', 'gps_location'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.8,
      evidenceWeights: { photo_evidence: 0.5, gps_location: 0.3, witness_attestation: 0.2 },
      minimumThreshold: 0.6,
    },
    temporal: { validDuration: 'P30D', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['commodity visual recognition', 'quantity estimation'],
      relatedPredicates: [
        WORKPROOF_PREDICATE_URIS.QuantityVerified,
        WORKPROOF_PREDICATE_URIS.OriginAuthenticated,
      ],
      contextTemplate: '{{commodity}} produced: {{quantity}} {{unit}}',
    },
  },
  QuantityVerified: {
    uri: WORKPROOF_PREDICATE_URIS.QuantityVerified,
    name: 'Quantity Verified',
    description: 'Production quantity independently confirmed',
    domain: 'asset',
    version: '2.1.0',
    schema: { type: 'number', min: 0 },
    evidence: { required: ['photo_evidence'], optional: ['assay_report'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.85,
      evidenceWeights: { photo_evidence: 0.4, assay_report: 0.6 },
      minimumThreshold: 0.7,
    },
    temporal: { validDuration: 'P30D', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['weight measurement', 'visual estimation cross-check'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.CommodityProduced],
      contextTemplate: 'Quantity verified: {{value}}',
    },
  },
  QualityGraded: {
    uri: WORKPROOF_PREDICATE_URIS.QualityGraded,
    name: 'Quality Graded',
    description: 'Quality assessment completed by authorized grader',
    domain: 'asset',
    version: '2.1.0',
    schema: { type: 'enum', values: ['high', 'medium', 'low'] },
    evidence: { required: ['assay_report'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.9, evidenceWeights: { assay_report: 1.0 }, minimumThreshold: 0.8 },
    temporal: { validDuration: 'P30D', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['assay report analysis'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.CommodityProduced],
      contextTemplate: 'Quality grade: {{value}}',
    },
  },
  OriginAuthenticated: {
    uri: WORKPROOF_PREDICATE_URIS.OriginAuthenticated,
    name: 'Origin Authenticated',
    description: 'Commodity provenance verified to specific extraction site',
    domain: 'asset',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['gps_location', 'photo_evidence'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.85,
      evidenceWeights: { gps_location: 0.5, photo_evidence: 0.3, site_audit: 0.2 },
      minimumThreshold: 0.7,
    },
    temporal: { validDuration: 'P30D', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['GPS matches registered site', 'satellite imagery correlation'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.SiteVerified],
      contextTemplate: 'Origin authenticated at site {{siteId}}',
    },
  },
  MethodCompliant: {
    uri: WORKPROOF_PREDICATE_URIS.MethodCompliant,
    name: 'Method Compliant',
    description: 'Production method meets required standards',
    domain: 'compliance',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['photo_evidence'], optional: ['site_audit'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.8,
      evidenceWeights: { photo_evidence: 0.5, site_audit: 0.5 },
      minimumThreshold: 0.6,
    },
    temporal: { validDuration: 'P90D', renewalRequired: true, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['production method visual analysis'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.EnvironmentalCompliance],
      contextTemplate: 'Production method compliant',
    },
  },

  // ─── Location Predicates ──────────────────────────────────────────────────
  SiteVerified: {
    uri: WORKPROOF_PREDICATE_URIS.SiteVerified,
    name: 'Site Verified',
    description: 'Production site confirmed through GPS and/or satellite imagery',
    domain: 'location',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['gps_location'], optional: ['photo_evidence'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'AuthorityID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.9,
      evidenceWeights: { gps_location: 0.7, photo_evidence: 0.3 },
      minimumThreshold: 0.7,
    },
    temporal: { validDuration: 'P1Y', renewalRequired: true, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['GPS coordinates within registered boundary'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.GeofenceCompliant],
      contextTemplate: 'Site verified at {{coordinates}}',
    },
  },
  GeofenceCompliant: {
    uri: WORKPROOF_PREDICATE_URIS.GeofenceCompliant,
    name: 'Geofence Compliant',
    description: 'Activity within authorized geographic boundary',
    domain: 'location',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['gps_location'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'AuthorityID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.95, evidenceWeights: { gps_location: 1.0 }, minimumThreshold: 0.8 },
    temporal: { validDuration: 'P1D', renewalRequired: false, monitoringType: 'continuous' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['geofence boundary check'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.SiteVerified],
      contextTemplate: 'Within authorized geofence',
    },
  },
  LocationConsistent: {
    uri: WORKPROOF_PREDICATE_URIS.LocationConsistent,
    name: 'Location Consistent',
    description: 'Location history aligns with reported production activities',
    domain: 'location',
    version: '2.1.0',
    schema: { type: 'number', min: 0, max: 1 },
    evidence: { required: ['gps_location'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.8,
      evidenceWeights: { gps_location: 1.0 },
      minimumThreshold: 0.6,
      decayModel: 'linear',
      halfLife: 30,
    },
    temporal: { validDuration: 'P7D', renewalRequired: false, monitoringType: 'continuous' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['location trajectory analysis', 'travel time feasibility'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.SiteVerified],
      contextTemplate: 'Location consistency score: {{value}}',
    },
  },
  EnvironmentalCompliance: {
    uri: WORKPROOF_PREDICATE_URIS.EnvironmentalCompliance,
    name: 'Environmental Compliance',
    description: 'Environmental standards met at production site',
    domain: 'compliance',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['site_audit'], optional: ['photo_evidence'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.85,
      evidenceWeights: { site_audit: 0.7, photo_evidence: 0.3 },
      minimumThreshold: 0.7,
    },
    temporal: { validDuration: 'P6M', renewalRequired: true, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['satellite deforestation check', 'water body proximity'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.MethodCompliant],
      contextTemplate: 'Environmental compliance verified',
    },
  },

  // ─── Compliance Predicates ────────────────────────────────────────────────
  InspectionPassed: {
    uri: WORKPROOF_PREDICATE_URIS.InspectionPassed,
    name: 'Inspection Passed',
    description: 'Regulatory or third-party inspection cleared',
    domain: 'compliance',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['document_hash'], optional: ['photo_evidence'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'AuthorityID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.95,
      evidenceWeights: { document_hash: 0.8, photo_evidence: 0.2 },
      minimumThreshold: 0.8,
    },
    temporal: { validDuration: 'P1Y', renewalRequired: true, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['inspection report analysis'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.StandardMet],
      contextTemplate: 'Inspection passed on {{effectiveAt}}',
    },
  },
  StandardMet: {
    uri: WORKPROOF_PREDICATE_URIS.StandardMet,
    name: 'Standard Met',
    description: 'Specific compliance standard requirement satisfied',
    domain: 'compliance',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.9, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P1Y', renewalRequired: true, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['standard reference validation'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.InspectionPassed],
      contextTemplate: 'Standard {{value}} met',
    },
  },
  GCIScoreRecorded: {
    uri: WORKPROOF_PREDICATE_URIS.GCIScoreRecorded,
    name: 'GCI Score Recorded',
    description: 'Compliance score snapshot from GCI engine',
    domain: 'compliance',
    version: '2.1.0',
    schema: { type: 'number', min: 0, max: 100 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'pattern', value: 'did:gtcx:gci:*' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.95, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.9 },
    temporal: { validDuration: 'P30D', renewalRequired: false, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['GCI score trend analysis'],
      relatedPredicates: [
        WORKPROOF_PREDICATE_URIS.InspectionPassed,
        WORKPROOF_PREDICATE_URIS.ViolationFree,
      ],
      contextTemplate: 'GCI score: {{value}}/100',
    },
  },
  ViolationFree: {
    uri: WORKPROOF_PREDICATE_URIS.ViolationFree,
    name: 'Violation Free',
    description: 'No compliance violations recorded during specified period',
    domain: 'compliance',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'AuthorityID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.85, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P90D', renewalRequired: true, monitoringType: 'continuous' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['violation database check'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.GCIScoreRecorded],
      contextTemplate: 'Violation-free period confirmed',
    },
  },
  LicenseValid: {
    uri: WORKPROOF_PREDICATE_URIS.LicenseValid,
    name: 'License Valid',
    description: 'Operating license current and valid',
    domain: 'compliance',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['government_id'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'AuthorityID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.95, evidenceWeights: { government_id: 1.0 }, minimumThreshold: 0.9 },
    temporal: {
      validDuration: 'P1Y',
      renewalRequired: true,
      monitoringType: 'event_triggered',
      triggers: ['permit.expired', 'permit.revoked'],
    },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['license expiry date check'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.InspectionPassed],
      contextTemplate: 'License valid until {{expiresAt}}',
    },
  },

  // ─── Financial Predicates ─────────────────────────────────────────────────
  PaymentReceived: {
    uri: WORKPROOF_PREDICATE_URIS.PaymentReceived,
    name: 'Payment Received',
    description: 'Income payment confirmed and recorded',
    domain: 'financial',
    version: '2.1.0',
    schema: { type: 'number', min: 0 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'FinanceID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.95, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.8 },
    temporal: { validDuration: 'P5Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['transaction record analysis'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.CommodityProduced],
      contextTemplate: 'Payment received: {{value}} {{unit}}',
    },
  },
  LoanDisbursed: {
    uri: WORKPROOF_PREDICATE_URIS.LoanDisbursed,
    name: 'Loan Disbursed',
    description: 'Credit disbursement received',
    domain: 'financial',
    version: '2.1.0',
    schema: { type: 'number', min: 0 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'FinanceID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.95, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.8 },
    temporal: { validDuration: 'P5Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['loan agreement analysis'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.RepaymentCompleted],
      contextTemplate: 'Loan disbursed: {{value}} {{unit}}',
    },
  },
  RepaymentCompleted: {
    uri: WORKPROOF_PREDICATE_URIS.RepaymentCompleted,
    name: 'Repayment Completed',
    description: 'Loan repayment obligation met',
    domain: 'financial',
    version: '2.1.0',
    schema: { type: 'number', min: 0 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'FinanceID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.95, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.8 },
    temporal: { validDuration: 'P5Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['repayment pattern analysis'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.LoanDisbursed],
      contextTemplate: 'Repayment completed: {{value}} {{unit}}',
    },
  },
  SavingsDeposited: {
    uri: WORKPROOF_PREDICATE_URIS.SavingsDeposited,
    name: 'Savings Deposited',
    description: 'Savings contribution recorded',
    domain: 'financial',
    version: '2.1.0',
    schema: { type: 'number', min: 0 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'FinanceID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.9, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P5Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['savings balance verification'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.PaymentReceived],
      contextTemplate: 'Savings deposited: {{value}} {{unit}}',
    },
  },
  TaxWithheld: {
    uri: WORKPROOF_PREDICATE_URIS.TaxWithheld,
    name: 'Tax Withheld',
    description: 'Tax obligation met through withholding',
    domain: 'financial',
    version: '2.1.0',
    schema: { type: 'number', min: 0 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'AuthorityID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.95, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.8 },
    temporal: { validDuration: 'P1Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['tax record verification'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.PaymentReceived],
      contextTemplate: 'Tax withheld: {{value}} {{unit}}',
    },
  },

  // ─── Learning Predicates ──────────────────────────────────────────────────
  ModuleCompleted: {
    uri: WORKPROOF_PREDICATE_URIS.ModuleCompleted,
    name: 'Module Completed',
    description: 'Training module finished with satisfactory completion',
    domain: 'composite',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.9, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P5Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['training completion assessment'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.AssessmentPassed],
      contextTemplate: 'Module completed: {{value}}',
    },
  },
  AssessmentPassed: {
    uri: WORKPROOF_PREDICATE_URIS.AssessmentPassed,
    name: 'Assessment Passed',
    description: 'Knowledge or skill assessment passed',
    domain: 'composite',
    version: '2.1.0',
    schema: { type: 'number', min: 0, max: 100 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.9, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P5Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['assessment score analysis'],
      relatedPredicates: [
        WORKPROOF_PREDICATE_URIS.ModuleCompleted,
        WORKPROOF_PREDICATE_URIS.CertificationEarned,
      ],
      contextTemplate: 'Assessment passed: {{value}}%',
    },
  },
  CertificationEarned: {
    uri: WORKPROOF_PREDICATE_URIS.CertificationEarned,
    name: 'Certification Earned',
    description: 'Formal certification or credential issued',
    domain: 'composite',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.95, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.8 },
    temporal: {
      validDuration: 'P3Y',
      renewalRequired: true,
      monitoringType: 'event_triggered',
      triggers: ['certification.expired'],
    },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['certification document verification'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.AssessmentPassed],
      contextTemplate: 'Certification earned: {{value}}',
    },
  },
  SkillDemonstrated: {
    uri: WORKPROOF_PREDICATE_URIS.SkillDemonstrated,
    name: 'Skill Demonstrated',
    description: 'Competency verified through practical demonstration',
    domain: 'composite',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['photo_evidence'], optional: ['witness_attestation'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.8,
      evidenceWeights: { photo_evidence: 0.5, witness_attestation: 0.5 },
      minimumThreshold: 0.6,
    },
    temporal: { validDuration: 'P2Y', renewalRequired: true },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['skill demonstration video/photo analysis'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.CertificationEarned],
      contextTemplate: 'Skill demonstrated: {{value}}',
    },
  },
  MentorshipProvided: {
    uri: WORKPROOF_PREDICATE_URIS.MentorshipProvided,
    name: 'Mentorship Provided',
    description: 'Teaching or mentoring others verified',
    domain: 'composite',
    version: '2.1.0',
    schema: { type: 'number', min: 0 },
    evidence: { required: ['witness_attestation'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
      minimumAttestors: 2,
    },
    confidence: {
      baseScore: 0.7,
      evidenceWeights: { witness_attestation: 1.0 },
      minimumThreshold: 0.5,
    },
    temporal: { validDuration: 'P1Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['mentorship session records'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.MentorshipReceived],
      contextTemplate: '{{value}} hours of mentorship provided',
    },
  },

  // ─── Performance Predicates ───────────────────────────────────────────────
  ConsistencyMaintained: {
    uri: WORKPROOF_PREDICATE_URIS.ConsistencyMaintained,
    name: 'Consistency Maintained',
    description: 'Regular reporting/activity pattern achieved',
    domain: 'temporal',
    version: '2.1.0',
    schema: { type: 'number', min: 0, max: 1 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'pattern', value: 'did:gtcx:*' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.9, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P30D', renewalRequired: false, monitoringType: 'continuous' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['activity frequency analysis', 'reporting gap detection'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.ReliabilityScore],
      contextTemplate: 'Consistency score: {{value}}',
    },
  },
  QualityThresholdMet: {
    uri: WORKPROOF_PREDICATE_URIS.QualityThresholdMet,
    name: 'Quality Threshold Met',
    description: 'Quality standard consistently achieved',
    domain: 'temporal',
    version: '2.1.0',
    schema: { type: 'boolean' },
    evidence: { required: ['assay_report'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'CertifierID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.9, evidenceWeights: { assay_report: 1.0 }, minimumThreshold: 0.8 },
    temporal: { validDuration: 'P90D', renewalRequired: true, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['quality trend analysis'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.QualityGraded],
      contextTemplate: 'Quality threshold met',
    },
  },
  ProductivityTarget: {
    uri: WORKPROOF_PREDICATE_URIS.ProductivityTarget,
    name: 'Productivity Target',
    description: 'Production target reached for specified period',
    domain: 'temporal',
    version: '2.1.0',
    schema: { type: 'number', min: 0 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.85, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P30D', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['production volume tracking'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.CommodityProduced],
      contextTemplate: 'Productivity target: {{value}}',
    },
  },
  ReliabilityScore: {
    uri: WORKPROOF_PREDICATE_URIS.ReliabilityScore,
    name: 'Reliability Score',
    description: 'Computed reliability metric based on activity patterns',
    domain: 'temporal',
    version: '2.1.0',
    schema: { type: 'number', min: 0, max: 1 },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'pattern', value: 'did:gtcx:*' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.85, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P30D', renewalRequired: false, monitoringType: 'continuous' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['reliability pattern computation'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.ConsistencyMaintained],
      contextTemplate: 'Reliability score: {{value}}',
    },
  },

  // ─── Community Predicates ─────────────────────────────────────────────────
  PeerEndorsement: {
    uri: WORKPROOF_PREDICATE_URIS.PeerEndorsement,
    name: 'Peer Endorsement',
    description: 'Fellow producer attestation of work quality or character',
    domain: 'relationship',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['witness_attestation'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
      minimumAttestors: 3,
    },
    confidence: {
      baseScore: 0.6,
      evidenceWeights: { witness_attestation: 1.0 },
      minimumThreshold: 0.4,
    },
    temporal: { validDuration: 'P1Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['social graph analysis', 'endorsement authenticity'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.CommunityMembership],
      contextTemplate: 'Peer endorsement: {{value}}',
    },
  },
  ElderAttestation: {
    uri: WORKPROOF_PREDICATE_URIS.ElderAttestation,
    name: 'Elder Attestation',
    description: 'Traditional authority or elder verification',
    domain: 'relationship',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['witness_attestation'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'AuthorityID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.7,
      evidenceWeights: { witness_attestation: 1.0 },
      minimumThreshold: 0.5,
    },
    temporal: { validDuration: 'P2Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['traditional authority verification', 'cultural protocol compliance'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.PeerEndorsement],
      contextTemplate: 'Elder attestation: {{value}}',
    },
  },
  CooperativeMembership: {
    uri: WORKPROOF_PREDICATE_URIS.CooperativeMembership,
    name: 'Cooperative Membership',
    description: 'Active membership in registered cooperative',
    domain: 'relationship',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['document_hash'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
    },
    confidence: { baseScore: 0.9, evidenceWeights: { document_hash: 1.0 }, minimumThreshold: 0.7 },
    temporal: { validDuration: 'P1Y', renewalRequired: true, monitoringType: 'periodic' },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['cooperative registration check'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.CommunityMembership],
      contextTemplate: 'Cooperative member: {{value}}',
    },
  },
  CommunityContribution: {
    uri: WORKPROOF_PREDICATE_URIS.CommunityContribution,
    name: 'Community Contribution',
    description: 'Verified contribution to community activities',
    domain: 'relationship',
    version: '2.1.0',
    schema: { type: 'string' },
    evidence: { required: ['witness_attestation'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
      minimumAttestors: 2,
    },
    confidence: {
      baseScore: 0.6,
      evidenceWeights: { witness_attestation: 1.0 },
      minimumThreshold: 0.4,
    },
    temporal: { validDuration: 'P1Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['community activity records'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.PeerEndorsement],
      contextTemplate: 'Community contribution: {{value}}',
    },
  },
  MentorshipReceived: {
    uri: WORKPROOF_PREDICATE_URIS.MentorshipReceived,
    name: 'Mentorship Received',
    description: 'Learning from community mentor verified',
    domain: 'relationship',
    version: '2.1.0',
    schema: { type: 'number', min: 0 },
    evidence: { required: ['witness_attestation'] },
    attestation: {
      allowedAttestors: [{ type: 'credential', value: 'ProducerID' }],
      selfAttestation: false,
    },
    confidence: {
      baseScore: 0.7,
      evidenceWeights: { witness_attestation: 1.0 },
      minimumThreshold: 0.5,
    },
    temporal: { validDuration: 'P1Y', renewalRequired: false },
    ai: {
      embeddingModel: 'text-embedding-3-large',
      reasoningHints: ['mentorship session records'],
      relatedPredicates: [WORKPROOF_PREDICATE_URIS.MentorshipProvided],
      contextTemplate: '{{value}} hours of mentorship received',
    },
  },
};
