import type { ComplianceConfig, RegulatoryFramework } from './types';

export function getDefaultFrameworks(config: ComplianceConfig): RegulatoryFramework[] {
  return [
    {
      code: 'LICENSE-001',
      title: 'Producer License',
      description: 'License required for commodity production operations',
      authority: 'regulatory_authority',
      category: 'licensing',
      jurisdiction: config.defaultJurisdiction,
      requirements: [
        {
          id: 'LICENSE-001-01',
          code: 'LICENSE-001-01',
          title: 'Valid Production License',
          description: 'Valid license for production operations',
          mandatory: true,
          applicableTo: ['producer'],
          verificationMethod: 'license_verification',
          renewalPeriod: 'annual',
          jurisdiction: config.defaultJurisdiction,
        },
      ],
      penalties: [{ violation: 'Operating without license', penalty: 'Fine and cessation' }],
      effectiveDate: '2024-01-01',
      lastUpdated: new Date().toISOString().split('T')[0] ?? new Date().toISOString(),
    },
    {
      code: 'TRADE-001',
      title: 'Trading License',
      description: 'License required for commodity trading',
      authority: 'trade_authority',
      category: 'licensing',
      jurisdiction: config.defaultJurisdiction,
      requirements: [
        {
          id: 'TRADE-001-01',
          code: 'TRADE-001-01',
          title: 'Licensed Trader Permit',
          description: 'Valid trading permit',
          mandatory: true,
          applicableTo: ['trader'],
          verificationMethod: 'license_verification',
          renewalPeriod: 'annual',
          jurisdiction: config.defaultJurisdiction,
        },
      ],
      penalties: [{ violation: 'Trading without license', penalty: 'Fine and closure' }],
      effectiveDate: '2024-01-01',
      lastUpdated: new Date().toISOString().split('T')[0] ?? new Date().toISOString(),
    },
    {
      code: 'AML-001',
      title: 'Anti-Money Laundering',
      description: 'AML requirements for high-value transactions',
      authority: 'financial_authority',
      category: 'financial',
      jurisdiction: config.defaultJurisdiction,
      requirements: [
        {
          id: 'AML-001-01',
          code: 'AML-001-01',
          title: 'Enhanced KYC',
          description: 'Enhanced verification for high-value transactions',
          mandatory: true,
          applicableTo: ['trader', 'exporter'],
          verificationMethod: 'kyc_verification',
          jurisdiction: config.defaultJurisdiction,
        },
      ],
      penalties: [{ violation: 'KYC failure', penalty: 'Investigation and sanctions' }],
      effectiveDate: '2024-01-01',
      lastUpdated: new Date().toISOString().split('T')[0] ?? new Date().toISOString(),
    },
    {
      code: 'ZKP-001',
      title: 'Zero-Knowledge Proof Validation',
      description: 'ZK proof verification for sensitive compliance assertions',
      authority: 'compliance_authority',
      category: 'operational',
      jurisdiction: config.defaultJurisdiction,
      requirements: [
        {
          id: 'ZKP-001-01',
          code: 'ZKP-001-01',
          title: 'Valid ZK Proof',
          description: 'Zero-knowledge proof must verify against declared inputs',
          mandatory: false,
          applicableTo: ['producer', 'trader', 'exporter'],
          verificationMethod: 'zk_proof_verification',
          jurisdiction: config.defaultJurisdiction,
        },
      ],
      penalties: [{ violation: 'Invalid proof submission', penalty: 'Manual review required' }],
      effectiveDate: '2026-01-01',
      lastUpdated: new Date().toISOString().split('T')[0] ?? new Date().toISOString(),
    },
  ];
}
