// ============================================================================
// @gtcx/verification
// Certificate generation, QR codes, and verification proofs for GTCX Protocol
// COMMODITY-AGNOSTIC ARCHITECTURE
// ============================================================================
//
// This package provides UNIVERSAL (platform-agnostic) verification infrastructure.
// It generates data structures that can be signed and stored by platform-specific code.
//
// KEY PRINCIPLE: Commodities are ATTRIBUTES, not types.
// The same certificate templates work for gold, silver, cocoa, coffee, or any commodity.
//
// Architecture:
// - Universal: This package (pure TypeScript, no platform dependencies)
// - Mobile: apps/mobile/shared/crypto/ (SecureStore, Expo)
// - Web: apps/web/shared/ (Web Crypto API)
// - Server: services/ (Node.js crypto)
// ============================================================================

// Types - including commodity-agnostic abstractions, predicates, claims, certificates, templates, proofs, and schemas
export {
  AIMetadata,
  AIMetadataSchema,
  AssetCategory,
  AssetCategorySchema,
  AssetForms,
  AssetLifecycleState,
  AssetLifecycleStateSchema,
  AssetLotData,
  AssetLotDataSchema,
  AttestationRules,
  AttestationRulesSchema,
  AttestorPattern,
  AttestorPatternSchema,
  BaseCertificateSchema,
  COMMODITY_CATEGORIES,
  COMMODITY_CONFIGS,
  Certificate,
  CertificateLocation,
  CertificateLocationSchema,
  CertificateMetadata,
  CertificateMetadataSchema,
  CertificateSecurityLevel,
  CertificateSecurityLevelSchema,
  CertificateTemplate,
  CertificateTemplateSchema,
  CertificateType,
  CertificateTypeSchema,
  CertificateVerificationData,
  CertificateVerificationDataSchema,
  CertificateVerificationResult,
  CertificateVerificationResultSchema,
  Claim,
  ClaimEvidence,
  ClaimEvidenceSchema,
  ClaimProof,
  ClaimProofSchema,
  ClaimSchema,
  CommodityConfig,
  CommodityConfigSchema,
  CommodityType,
  CommodityTypeSchema,
  ComplianceData,
  ComplianceDataSchema,
  ConfidenceRules,
  ConfidenceRulesSchema,
  CredentialSubtypes,
  CredentialType,
  CredentialTypeSchema,
  CommodityOriginProfileId,
  CommodityOriginZkProofRef,
  CommodityOriginZkProofRefSchema,
  CryptographicProofRef,
  CryptographicProofRefSchema,
  CustodyEntry,
  EnvironmentalFactors,
  EnvironmentalFactorsSchema,
  EvidenceRequirements,
  EvidenceRequirementsSchema,
  EvidenceType,
  EvidenceTypeSchema,
  ExtractionSiteSubtypes,
  GeneratedQRCode,
  GeneratedQRCodeSchema,
  GeologicalContext,
  GoldLotData,
  LocationProofRef,
  LocationProofRefSchema,
  MeasurementUnit,
  MeasurementUnitSchema,
  MilitaryGradeCertificate,
  MilitaryGradeCertificateSchema,
  MultiSignature,
  MultiSignatureSchema,
  OperatorRole,
  OperatorRoleSchema,
  OperatorTier,
  OperatorTierSchema,
  PhotoEvidenceRef,
  PhotoEvidenceRefSchema,
  PhotoProofRef,
  PhotoProofRefSchema,
  PredicateDefinition,
  PredicateDefinitionSchema,
  PredicateDomain,
  PredicateDomainSchema,
  PredicateSchema,
  PredicateSchemaSchema,
  PredicateURI,
  PredicateURISchema,
  ProofBundle,
  ProofBundleSchema,
  QRCodeData,
  QRCodeDataSchema,
  QRCodeMetadata,
  QRCodeMetadataSchema,
  QRCodeType,
  QRCodeTypeSchema,
  QRCodeVerificationResult,
  QRCodeVerificationResultSchema,
  QualityGrade,
  QualityGradeSchema,
  ROLE_TO_CREDENTIAL,
  ResourceContext,
  ResourceContextSchema,
  SettlementRecord,
  SiteCategory,
  SiteCategorySchema,
  SiteReference,
  SiteReferenceSchema,
  SiteType,
  SiteTypeSchema,
  SiteTypes,
  StandardCertificate,
  StandardCertificateSchema,
  TemporalRules,
  TemporalRulesSchema,
  ValidationMetrics,
  ValidationMetricsSchema,
  ValidationRule,
  ValidationRuleSchema,
  getCommodityCategory,
  getCommodityConfig,
  getCredentialForRole,
  migrateGoldLotData,
  migrateLegacyLotData,
} from './types';

// Migration helpers for cross-repo predicate reconciliation (ADR-012)
export {
  TRADEPASS_LEGACY_ID_ALIASES,
  findLegacyIdsForUri,
  resolveLegacyPredicateId,
} from './migration';

// QR Code generation
export {
  QRCodeConfig,
  createAssetLotQRData,
  createCertificateQRData,
  createGoldLotQRData,
  createLocationQRData,
  createPhotoQRData,
  createQRCodeStructure,
  generateQRCodeId,
  getQRCodeCommodityType,
  hashQRCodeContent,
  parseQRData,
  serializeQRData,
  verifyQRCodeData,
} from './qr';

// Certificate generation
export {
  ASSET_ORIGIN_TEMPLATE,
  CERTIFICATE_TEMPLATES,
  COMMODITY_CERTIFICATE_CONFIGS,
  COMPLIANCE_TEMPLATE,
  CUSTODY_TRANSFER_TEMPLATE,
  CommodityCertificateConfig,
  CreateCertificateInput,
  GOLD_ORIGIN_TEMPLATE,
  GOVERNMENT_INSPECTOR_TEMPLATE,
  LOCATION_TEMPLATE,
  PHOTO_TEMPLATE,
  RevocationChecker,
  RevocationEntry,
  RevocationStatus,
  SETTLEMENT_TEMPLATE,
  VerificationError,
  WORK_SITE_TEMPLATE,
  assertNotRevoked,
  checkRevocationStatus,
  createCertificateMetadata,
  createCommodityCertificateConfig,
  createDefaultEnvironmentalFactors,
  createDefaultValidationMetrics,
  createDenyAllRevocationChecker,
  createInMemoryRevocationChecker,
  createMilitaryGradeCertificateData,
  createNoopRevocationChecker,
  createStandardCertificateData,
  formatCertificateForDisplay,
  generateCertificateId,
  getCertificateAge,
  getCertificateCommodityType,
  getCommodityCertificateConfig,
  getEffectiveTemplate,
  getTemplate,
  getTemplatesBySecurityLevel,
  getTemplatesByType,
  isCertificateExpired,
  listTemplateIds,
  validateCertificateInput,
  verifyCertificateStructure,
} from './certificates';

// Proof bundling
export {
  CreateProofBundleInput,
  LocationProofInput,
  PhotoProofInput,
  createCryptographicProofRef,
  createLocationProof,
  createPhotoProof,
  attachCommodityOriginZkProof,
  commodityOriginWitnessToProfileInput,
  commodityOriginZkProofRefToProfileProof,
  createCommodityOriginZkProofRef,
  createProofBundle,
  DEFAULT_LAB_MERKLE_PATH_HEX,
  extractProofHashes,
  generateProofBundleId,
  getProofBundleSummary,
  hashProofBundle,
  parseProofBundle,
  serializeProofBundle,
  verifyCommodityOriginZkProofCryptographic,
  verifyCommodityOriginZkProofStructure,
  verifyProofBundleStructure,
  type CommodityOriginWitnessLike,
} from './proofs';

// ============================================================================
// TRACED OPERATIONS (AI-Native)
// Import traced versions for operation logging and AI analysis
// ============================================================================

export {
  tracedGenerateCertificate,
  tracedVerifyCertificate,
  tracedGenerateQRCode,
  tracedVerifyQRCode,
  tracedCreateProofBundle,
  tracedVerificationWorkflow,
  logComplianceEvent,
  logGCICalculation,
  computeVerificationSummary,
  type GenerateCertificateInput,
  type GenerateQRCodeInput,
  type VerificationOperationLog,
  type VerificationSummary,
} from './traced';
